version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  node-logger-swagger:
    build:
      context: ./node-logger-swagger
      dockerfile: Dockerfile
    container_name: node-logger-swagger
    ports:
      - "3000:3000"
    environment:
      - DBCONFIG=mongodb://mongo:27017/logs
    depends_on:
      - mongo


volumes:
  mongo-data:
  rabbitmq-data:
